# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5, unique=True)),
                ('long_name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='pollutant',
            name='sensor',
            field=models.ManyToManyField(to='CitiSense.Sensor'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pollutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitiSense.Pollutant'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitiSense.Sensor'),
        ),
    ]
